spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qingxinjiajiao?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
